savePrefix: ''
engineStrict: true
ignoreScripts: true
sideEffectsCache: false
strictPeerDependencies: false
minimumReleaseAge: 1440 # 1 day. Increase it to 4320 (3 days).
allowBuilds:
    esbuild: true
